management:
  health:
    defaults:
      #开启健康检查
      enabled: true


springfox:
  documentation:
    swagger:
      v2:
        #默认选项
        path: /api-docs
info:
    app:
      #导入pom文件信息
      name: '@project.name@'
      description: '@project.description@'
      version: '@project.version@'
      parent-version: '@project.parent.version@'

name: buhao